"""TDD tests for Runtime lifecycle ownership: lifecycle bats deployment, bat sovereignty, and auto-kill."""

from pathlib import Path
import pytest

from app.runtimes.work_runtime import WorkRuntime, WorkerSlot


# =============================================================================
# Test 1: Lifecycle bats are copied to worker slot during dispatch
# =============================================================================

def test_dispatch_next_deploys_lifecycle_bats_to_worker_slot(tmp_path):
    """dispatch_next deploys Online.bat/StartWriting.bat/Done.bat into the worker slot directory."""
    # Setup directory structure
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir()
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    # Lifecycle bats source dir
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)
    for bat_name in ["Online.bat", "StartWriting.bat", "Done.bat", "signal_bridge.py", "BOOTSTRAP.txt"]:
        (tools_dir / bat_name).write_text(f"@echo off\necho {bat_name}", encoding="utf-8")

    # Create a task file
    task_file = queue_dir / "task_001.txt"
    task_file.write_text(
        "TASK_ID: t_001\nFEATURE_ID: f_test\nPOOL: work\n\ntest body",
        encoding="utf-8",
    )

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18810)

    # Inject tools_dir so WorkRuntime can find lifecycle bats
    runtime._lifecycle_tools_dir = tools_dir

    # Mock LaunchManager.launch to avoid real process spawning
    import app.shared.launch_manager as lm_module
    original_launch = lm_module.LaunchManager.launch

    def mock_launch(self, request, dry_run=True):
        return {
            "launched": True,
            "dry_run": dry_run,
            "command": ["cmd"],
            "cwd": str(tmp_path),
            "pid": 9999,
            "job_handle": 0xDEAD,
        }

    lm_module.LaunchManager.launch = mock_launch
    try:
        result = runtime.dispatch_next(dry_run=True)

        assert result["dispatched"] is True

        # Lifecycle bats MUST exist in worker slot directory
        for bat_name in ["Online.bat", "StartWriting.bat", "Done.bat"]:
            bat_path = worker1_dir / bat_name
            assert bat_path.exists(), f"{bat_name} not deployed to worker slot"
            # Content should match source (not empty)
            content = bat_path.read_text(encoding="utf-8")
            assert len(content) > 0, f"{bat_name} deployed but empty"

        # Non-work-pool bats should NOT be deployed
        assert not (worker1_dir / "StartThinking.bat").exists()

    finally:
        lm_module.LaunchManager.launch = original_launch


# =============================================================================
# Test 2: dispatch_next respects Runtime-generated bat (no LaunchManager overwrite)
# =============================================================================

def test_dispatch_next_generated_bat_not_overwritten_by_launch_manager(tmp_path):
    """The bat generated by RuntimePromptBuilder is NOT overwritten by LaunchManager."""
    # Setup directory structure
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir()
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)
    for bat_name in ["Online.bat", "StartWriting.bat", "Done.bat", "signal_bridge.py", "BOOTSTRAP.txt"]:
        (tools_dir / bat_name).write_text(f"@echo off\necho {bat_name}", encoding="utf-8")

    # Create task
    task_file = queue_dir / "task_002.txt"
    task_file.write_text(
        "TASK_ID: t_002\nFEATURE_ID: f_test\nPOOL: work\n\ntest body",
        encoding="utf-8",
    )

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18811)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_launch = lm_module.LaunchManager.launch
    original_build_cmd = lm_module.LaunchManager.build_command

    def mock_launch(self, request, dry_run=True):
        return {
            "launched": True,
            "dry_run": dry_run,
            "command": ["cmd"],
            "cwd": str(tmp_path),
            "pid": 9999,
            "job_handle": 0xDEAD,
        }

    lm_module.LaunchManager.launch = mock_launch

    # Track if _ensure_launch_bat was called
    ensure_called = []

    original_ensure = lm_module.LaunchManager._ensure_launch_bat

    def tracked_ensure(self, request):
        ensure_called.append(request.bat_path)
        # DO NOT call original — simulating the fix

    lm_module.LaunchManager._ensure_launch_bat = tracked_ensure

    try:
        result = runtime.dispatch_next(dry_run=True)
        assert result["dispatched"] is True

        bat_file = worker1_dir / "launch_worker_01.bat"
        assert bat_file.exists(), "launch bat not generated"

        # CRITICAL: _ensure_launch_bat should NOT be called when bat already exists
        # OR LaunchManager should not regenerate the bat
        # After fix: bat content should be from RuntimePromptBuilder, not DIRECT_BOOTSTRAP_PROMPT

        bat_content = bat_file.read_text(encoding="utf-8")

        # The fixed bat should NOT contain DIRECT_BOOTSTRAP_PROMPT
        assert "Read BOOTSTRAP.txt" not in bat_content, (
            "Bat still contains old BOOTSTRAP prompt — LaunchManager overwrote Runtime-generated bat"
        )

        # The fixed bat SHOULD contain evidence of Runtime prompt injection
        # Either task_id from RuntimePromptBuilder OR lifecycle bat calls
        assert ("Online.bat" in bat_content or "t_002" in bat_content), (
            "Bat does not contain Runtime-injected content"
        )

    finally:
        lm_module.LaunchManager.launch = original_launch
        lm_module.LaunchManager.build_command = original_build_cmd
        lm_module.LaunchManager._ensure_launch_bat = original_ensure


# =============================================================================
# Test 3: handle_signal kills worker process on terminal signal
# =============================================================================

def test_handle_signal_kills_worker_on_done(tmp_path):
    """handle_signal calls cleanup_launch when done/failed/blocked signal is received."""
    # Setup
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir()
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)
    for bat_name in ["Online.bat", "StartWriting.bat", "Done.bat"]:
        (tools_dir / bat_name).write_text(f"@echo off\necho {bat_name}", encoding="utf-8")

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18812)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_cleanup = lm_module.LaunchManager.cleanup_launch

    cleanup_calls = []

    def tracked_cleanup(self, launch_result):
        cleanup_calls.append(launch_result)
        return {"cleaned": True, "job_handle": launch_result.get("job_handle")}

    lm_module.LaunchManager.cleanup_launch = tracked_cleanup

    # Mark slot as busy with a launch_result that includes job_handle
    slot = runtime.get_slot("worker_01")
    assert slot is not None
    slot.busy = True
    slot.assigned_task_id = "t_003"
    slot.launch_result = {
        "launched": True,
        "pid": 12345,
        "job_handle": 0xBEEF,
    }

    try:
        # Send done signal
        signal_result = {
            "agent_id": "worker_01",
            "task_id": "t_003",
            "signal": "done",
            "is_terminal": True,
        }

        runtime.handle_signal(signal_result)

        # CRITICAL: cleanup_launch MUST have been called
        assert len(cleanup_calls) == 1, (
            f"cleanup_launch not called. Expected 1 call, got {len(cleanup_calls)}. "
            "handle_signal does not kill worker on terminal signal."
        )

        # The job_handle must be passed through
        assert cleanup_calls[0].get("job_handle") == 0xBEEF, (
            "job_handle not passed to cleanup_launch"
        )

        # Slot should also be released
        assert slot.busy is False
        assert slot.assigned_task_id == ""

    finally:
        lm_module.LaunchManager.cleanup_launch = original_cleanup


def test_handle_signal_kills_worker_on_failed(tmp_path):
    """handle_signal calls cleanup_launch when failed signal is received."""
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_01" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18813)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_cleanup = lm_module.LaunchManager.cleanup_launch
    cleanup_calls = []

    def tracked_cleanup(self, launch_result):
        cleanup_calls.append(launch_result)
        return {"cleaned": True}

    lm_module.LaunchManager.cleanup_launch = tracked_cleanup

    slot = runtime.get_slot("worker_01")
    slot.busy = True
    slot.assigned_task_id = "t_004"
    slot.launch_result = {"launched": True, "pid": 54321, "job_handle": 0xCAFE}

    try:
        runtime.handle_signal({
            "agent_id": "worker_01",
            "task_id": "t_004",
            "signal": "failed",
            "is_terminal": True,
        })

        assert len(cleanup_calls) == 1, f"cleanup_launch not called on failed. Got {len(cleanup_calls)}"
        assert slot.busy is False

    finally:
        lm_module.LaunchManager.cleanup_launch = original_cleanup


def test_handle_signal_kills_worker_on_blocked(tmp_path):
    """handle_signal calls cleanup_launch when blocked signal is received."""
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_01" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18814)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_cleanup = lm_module.LaunchManager.cleanup_launch
    cleanup_calls = []

    def tracked_cleanup(self, launch_result):
        cleanup_calls.append(launch_result)
        return {"cleaned": True}

    lm_module.LaunchManager.cleanup_launch = tracked_cleanup

    slot = runtime.get_slot("worker_01")
    slot.busy = True
    slot.assigned_task_id = "t_005"
    slot.launch_result = {"launched": True, "pid": 11111, "job_handle": 0xFEED}

    try:
        runtime.handle_signal({
            "agent_id": "worker_01",
            "task_id": "t_005",
            "signal": "blocked",
            "is_terminal": True,
        })

        assert len(cleanup_calls) == 1, f"cleanup_launch not called on blocked. Got {len(cleanup_calls)}"
        assert slot.busy is False

    finally:
        lm_module.LaunchManager.cleanup_launch = original_cleanup


# =============================================================================
# Test 4: Non-terminal signals do NOT trigger cleanup
# =============================================================================

def test_handle_signal_does_not_kill_on_non_terminal_signals(tmp_path):
    """online and start_writing signals do NOT trigger cleanup_launch."""
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_01" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18815)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_cleanup = lm_module.LaunchManager.cleanup_launch
    cleanup_calls = []

    def tracked_cleanup(self, launch_result):
        cleanup_calls.append(launch_result)
        return {"cleaned": True}

    lm_module.LaunchManager.cleanup_launch = tracked_cleanup

    slot = runtime.get_slot("worker_01")
    slot.busy = True
    slot.assigned_task_id = "t_006"
    slot.launch_result = {"launched": True, "pid": 22222, "job_handle": 0xFACE}

    try:
        # online signal — should NOT trigger cleanup
        runtime.handle_signal({
            "agent_id": "worker_01",
            "task_id": "t_006",
            "signal": "online",
            "is_terminal": False,
        })
        assert len(cleanup_calls) == 0, "cleanup_launch called on online signal"
        assert slot.busy is True, "slot released prematurely on online"

        # start_writing signal — should NOT trigger cleanup
        runtime.handle_signal({
            "agent_id": "worker_01",
            "task_id": "t_006",
            "signal": "start_writing",
            "is_terminal": False,
        })
        assert len(cleanup_calls) == 0, "cleanup_launch called on start_writing signal"
        assert slot.busy is True, "slot released prematurely on start_writing"

    finally:
        lm_module.LaunchManager.cleanup_launch = original_cleanup


# =============================================================================
# Test 6: dispatch_next configures LaunchRequest for visible window + job cleanup
# =============================================================================

def test_dispatch_next_enables_job_object_and_visible_console(tmp_path):
    """dispatch_next creates LaunchRequest with use_job_object=True and create_new_console=True."""
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir()
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)
    for file_name in ["Online.bat", "StartWriting.bat", "Done.bat", "signal_bridge.py", "BOOTSTRAP.txt"]:
        (tools_dir / file_name).write_text(f"mock {file_name}", encoding="utf-8")

    task_file = queue_dir / "task_008.txt"
    task_file.write_text(
        "TASK_ID: t_008\nFEATURE_ID: f_test\nPOOL: work\n\ntest body",
        encoding="utf-8",
    )

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18820)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_launch = lm_module.LaunchManager.launch

    captured_requests = []

    def mock_launch(self, request, dry_run=True):
        captured_requests.append(request)
        return {
            "launched": True,
            "dry_run": dry_run,
            "command": ["cmd"],
            "cwd": str(tmp_path),
            "pid": 9999,
            "job_handle": 0xBEEF,
        }

    lm_module.LaunchManager.launch = mock_launch

    try:
        result = runtime.dispatch_next(dry_run=True)

        assert result["dispatched"] is True
        assert len(captured_requests) == 1, f"Expected 1 launch call, got {len(captured_requests)}"

        req = captured_requests[0]
        assert req.use_job_object is True, (
            "use_job_object must be True for process cleanup via Job Object"
        )
        assert req.create_new_console is True, (
            "create_new_console must be True for visible worker window"
        )
        # bootstrap_path should stay None to protect Runtime-generated bat
        assert req.bootstrap_path is None, (
            "bootstrap_path must be None so Runtime-generated bat is not overwritten"
        )

    finally:
        lm_module.LaunchManager.launch = original_launch


# =============================================================================
# Test 7: handle_signal skips cleanup if no launch_result (no-op safety)
# =============================================================================

def test_handle_signal_no_crash_when_no_launch_result(tmp_path):
    """handle_signal does not crash if slot has no launch_result (already cleaned up)."""
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_01" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18816)
    runtime._lifecycle_tools_dir = tools_dir

    slot = runtime.get_slot("worker_01")
    slot.busy = True
    slot.assigned_task_id = "t_007"
    slot.launch_result = None  # No launch result

    # Should NOT crash
    runtime.handle_signal({
        "agent_id": "worker_01",
        "task_id": "t_007",
        "signal": "done",
        "is_terminal": True,
    })

    # Slot should still be released
    assert slot.busy is False

# =============================================================================
# Test 8: Slot directory is cleaned up on terminal signals
# =============================================================================

def test_slot_cleanup_on_done_signal(tmp_path):
    """Verify slot directory is cleaned (except workspace) after done signal."""
    # Setup directory structure
    queue_dir = tmp_path / "pools" / "work" / "Queue"
    queue_dir.mkdir(parents=True)
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir()
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    
    tools_dir = tmp_path / "runtime" / "tools"
    tools_dir.mkdir(parents=True)
    for bat_name in ["Online.bat", "StartWriting.bat", "Done.bat", "signal_bridge.py", "BOOTSTRAP.txt"]:
        (tools_dir / bat_name).write_text(f"mock {bat_name}", encoding="utf-8")

    # Create task
    task_file = queue_dir / "task_cleanup.txt"
    task_file.write_text("TASK_ID: t_cleanup\n\nbody", encoding="utf-8")

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18890)
    runtime._lifecycle_tools_dir = tools_dir

    import app.shared.launch_manager as lm_module
    original_launch = lm_module.LaunchManager.launch
    original_cleanup = lm_module.LaunchManager.cleanup_launch

    def mock_launch(self, request, dry_run=True):
        return {"launched": True, "job_handle": 0x1, "pid": 1}

    def mock_cleanup(self, launch_result):
        return {"cleaned": True}

    lm_module.LaunchManager.launch = mock_launch
    lm_module.LaunchManager.cleanup_launch = mock_cleanup

    try:
        # Dispatch task to worker_01
        runtime.dispatch_next(dry_run=True)
        slot = runtime.get_slot("worker_01")
        
        # Add a dummy file inside workspace to ensure it isn't deleted
        (slot.workspace_dir / "output.txt").write_text("result")
        
        # Verify deployed files exist
        assert (slot.slot_dir / "BOOTSTRAP.txt").exists()
        assert (slot.slot_dir / "Online.bat").exists()
        assert (slot.slot_dir / "task_cleanup.txt").exists()
        assert (slot.slot_dir / "launch_worker_01.bat").exists()

        # Send done signal
        runtime.handle_signal({
            "agent_id": "worker_01",
            "task_id": "t_cleanup",
            "signal": "done",
            "is_terminal": True,
        })

        # Verify cleanup
        assert not (slot.slot_dir / "BOOTSTRAP.txt").exists(), "BOOTSTRAP.txt should be deleted"
        assert not (slot.slot_dir / "Online.bat").exists(), "Online.bat should be deleted"
        assert not (slot.slot_dir / "task_cleanup.txt").exists(), "Task file should be deleted"
        assert not (slot.slot_dir / "launch_worker_01.bat").exists(), "Launch bat should be deleted"
        
        # Verify workspace remains
        assert slot.workspace_dir.exists(), "Workspace directory must be preserved"
        assert (slot.workspace_dir / "output.txt").exists(), "Workspace contents must be preserved"

    finally:
        lm_module.LaunchManager.launch = original_launch
        lm_module.LaunchManager.cleanup_launch = original_cleanup


def test_slot_cleanup_on_timeout(tmp_path):
    """Verify slot directory is cleaned (except workspace) on timeout."""
    import time
    
    # Setup
    worker1_dir = tmp_path / "pools" / "work" / "worker_01"
    worker1_dir.mkdir(parents=True)
    (worker1_dir / "workspace").mkdir()
    (tmp_path / "pools" / "work" / "worker_02" / "workspace").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Outbox").mkdir(parents=True)
    (tmp_path / "pools" / "work" / "Queue").mkdir(parents=True)

    runtime = WorkRuntime(root_dir=tmp_path, signal_port=18891)
    
    import app.shared.launch_manager as lm_module
    original_cleanup = lm_module.LaunchManager.cleanup_launch
    lm_module.LaunchManager.cleanup_launch = lambda self, res: {"cleaned": True}

    try:
        slot = runtime.get_slot("worker_01")
        slot.busy = True
        slot.assigned_task_id = "t_timeout"
        slot.assigned_at_epoch = time.time() - 400  # Timed out
        slot.timeout_seconds = 300
        slot.launch_result = {"launched": True}

        # Create dummy deployed files
        (slot.slot_dir / "dummy.bat").write_text("test")
        (slot.slot_dir / "BOOTSTRAP.txt").write_text("test")

        # Run timeout check
        timed_out = runtime.check_timeouts()
        
        assert len(timed_out) == 1
        assert not (slot.slot_dir / "dummy.bat").exists(), "dummy.bat should be deleted on timeout"
        assert not (slot.slot_dir / "BOOTSTRAP.txt").exists(), "BOOTSTRAP.txt should be deleted on timeout"
        assert slot.workspace_dir.exists(), "Workspace directory must be preserved"

    finally:
        lm_module.LaunchManager.cleanup_launch = original_cleanup
